name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: rustup default 1.65.0 && rustup component add clippy
    - uses: actions/checkout@v4
    - name: Run clippy
      run: cargo clippy
    - name: Run tests for base crate
      run: cargo test
    - name: Run tests for std crate
      run: cargo test --manifest-path std/Cargo.toml

